[package]
name = "aava"
edition = "2024"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies]
walrus = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/walrus", rev = "main" }
wal = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/wal", rev = "main" }